wallpaper {
    monitor = DP-2
    path = ~/Pictures/wallpapers/images/wall2.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpapers/images/wall2.png
    fit_mode = cover
}

splash = false
