general {
    ignore_empty_input = true
}

input-field {
    monitor = 
    size = 300, 45
    outer_color = rgba(255,255,255,0.3)
    inner_color = rgba(70,70,70,3.0)
    font_color = rgba(255,255,255,1.0)
    fade_on_empty = false
    check_color = rgba(255,255,255,1.0)
    position = 
    
}

background {
    path = /home/zan/Pictures/wallpapers/images/wall2_upscaled.jpeg
    blur_passes = 3
}

label {
    monitor =
    text = $TIME
    color = rgb(ffffff)
    font_size = 96
    font_family = SF Pro Display
    position = 0, 128
    halign = center
    valign = center
}
