-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- #######################################################################################

-- AUTOGENERATED HYPR CONFIG.

-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,

-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--## MONITORS ###

--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
    output   = "DP-2",
    mode     = "1920x1080@144",
    position = "0x0",
    scale    = 1,
})

hl.monitor({
    output   = "HDMI-A-1",
    mode     = "1920x1080",
    position = "1920x0",
    scale    = 1,
})

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use

local terminal = "kitty"

local fileManager = "dolphin"

local discord = discord

local screenShot = "hyprshot -m region --clipboard-only"

local appLauncher = "rofi -show drun"

local workSpaceChanger = "/home/zan/.config/hypr/scripts/workspace_change"

local moveWindowToWorkspace = "/home/zan/.config/hypr/scripts/move_window_to_workspace"

local changeMode = "/home/zan/.config/hypr/scripts/change_mode"

--################

--## AUTOSTART ###

--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)

-- Or execute your favorite apps at launch like this:










--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_THEME", "BreezeX-RosePine-Linux")

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("QT_STYLE_OVERRIDE", "kvantum")

hl.env("QT_QPA_PALETTE_OVERRIDE", 1)

hl.env("CRYPTOGRAPHY_OPENSSL_NO_LEGACY", 1)

hl.env("XDG_MENU_PREFIX", "arch-")

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

hl.config({
    cursor = {
        no_hardware_cursors = true,
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
    general = {
        gaps_in = 2,
        gaps_out = 5,
        border_size = 2,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = "rgba(ffffffff)",
            inactive_border = "rgba(595959aa)",
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
    decoration = {
        rounding = 10,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 3,
            passes = 2,
            vibrancy = 0.1696,
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#animations

hl.config({
    animations = {
        enabled = true,
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
})
hl.curve("myBezier", {
    type = "bezier",
    points = { { 0.05, 0.9 }, { 0.1, 1.05 } },
})
hl.animation({ leaf = "windows", enabled = true, speed = 7, bezier = "myBezier" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 7, bezier = "myBezier", style = "popin 80%" })
hl.animation({ leaf = "border", enabled = true, speed = 10, bezier = "myBezier" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 8, bezier = "myBezier" })
hl.animation({ leaf = "fade", enabled = true, speed = 7, bezier = "myBezier" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 6, bezier = "myBezier" })

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
    dwindle = {
        preserve_split = true,
        -- You probably want this
    },
})

hl.config({
    debug = {
        full_cm_proto = true,
    },
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
    master = {
        new_status = "master",
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
    misc = {
        force_default_wallpaper = -1,
        -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false,
        -- If true disables the random hyprland logo / anime girl background. :(
        disable_splash_rendering = true,
    },
})

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "si",
        kb_model = "pc104",
        follow_mouse = 2,
        accel_profile = "flat",
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures

hl.config({
    gestures = {
        --workspace_swipe = false
    },
})

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

--###################

--## KEYBINDINGSS ###

--###################

-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modifier

-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("kitty"))

hl.bind(mainMod .. " + " .. "C", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("dolphin"))

hl.bind(mainMod .. " + " .. "V", hl.dsp.exec_cmd("/home/zan/.config/hypr/scripts/change_mode"))

hl.bind("PRINT", hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"))

hl.bind(mainMod .. " + " .. "L", hl.dsp.exec_cmd("rofi -show drun"))

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mainMod .. " + " .. "M", hl.dsp.window.fullscreen())

-- Move focus with mainMod + arrow keys

hl.bind(mainMod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mainMod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.exec_cmd("/home/zan/.config/hypr/scripts/workspace_change"))

hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.exec_cmd("/home/zan/.config/hypr/scripts/workspace_change"))

hl.bind(mainMod .. " + " .. "Z", hl.dsp.exec_cmd("/home/zan/.config/hypr/scripts/move_window_to_workspace"))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

-- Move/resize windows with mainMod + LMB/RMB and dragging

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

--#############################

--## WINDOWS AND WORKSPACES ###

--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

-- Example windowrule v1

-- Example windowrule v2

hl.workspace_rule({
    workspace = 1,
    monitor = "DP-2",
})

hl.workspace_rule({
    workspace = 2,
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = 3,
    monitor = "HDMI-A-1",
})

hl.window_rule({
    name  = "suppress_event_maxim",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- You'll probably like this.

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(rofi)$",
    },
    float = true,
})

hl.window_rule({
    name  = "border_color_rgba_ff",
    match = {
        class = "^(kitty)$",
    },
    border_color = "rgba(ffffffff)",
    border_size = 2,
})

hl.window_rule({
    name  = "workspace_2_silent",
    match = {
        class = "^(discord)$",
    },
    workspace = "2 silent",
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(nm-connection-editor)$",
    },
    float = true,
})

hl.window_rule({
    name  = "float_on",
    match = {
        class = "^(org.pulseaudio.pavucontrol)$",
    },
    float = true,
    size = { 1000, 500 },
})

hl.layer_rule({
    match = {
        namespace = "rofi",
    },
    blur = true,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("/home/zan/.config/hypr/scripts/keyboard_color")
    hl.exec_cmd("dunst")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprctl setcursor rose-pine-hyprcursor 24")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme BreezeX-RosePine-Linux")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-size 24")
    hl.exec_cmd("systemctl --user start xdg-desktop-portal.service --ignore-dependencies")
end)
