preload = /home/zan/Pictures/wallpapers/wall2_upscaled.jpeg

wallpaper = eDP-1,/home/zan/Pictures/wallpapers/wall2_upscaled.jpeg


#enable splash text rendering over the wallpaper
splash = false

#fully disable ipc
# ipc = off
