#!/bin/bash

mode=$(hyprctl activewindow | grep -w "floating:" | sed -n "1p" | tr "\\t" " ")

if [ "$mode" == " floating: 0" ]; then
	hyprctl dispatch 'hl.dsp.window.float({ action = "set" })'
else
	hyprctl dispatch 'hl.dsp.window.float({ action = "unset" })'
fi
