#!/bin/bash

workspace=$(cat /home/zan/.config/hypr/scripts/counter)

if [ "$workspace" == "2" ]; then
	hyprctl dispatch 'hl.dsp.window.move({ workspace = "3", follow = false })'
else
	hyprctl dispatch 'hl.dsp.window.move({ workspace = "2", follow = false })'
fi
